config/routes.rb
Rails.application.routes.draw do
  resources :interventions
  resources :leads  
  devise_for :users

  # get "leads", to: "leads#new"
  # post "leads", to: "leads#create"
  # get "leads/index", to: "leads#index"
  
  post "/", to: "leads#create"
  get "quotes", to: "quotes#new"
  post "quotes", to: "quotes#create"

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "home#index"
  get "commercial",  to: "home#commercial"
  get "residential", to: "home#residential"
  get "interventions", to: "interventions#interventions"
  
  resources :synthesized_messages
end
  
  #Dropdown dynamic menu

  Rails.application.routes.draw do

    resources :testing_buttons
    get 'get_building_by_customer/:customer_id', to: 'interventions#get_building_by_customer'  
    get 'get_battery_by_building/:building_id', to: 'interventions#get_battery_by_building'  
    get 'get_column_by_battery/:battery_id', to: 'interventions#get_column_by_battery' 
    get 'get_elevator_by_column/:column_id', to: 'interventions#get_elevator_by_column'  
    get '/building_search' => 'application#building_search'
  
   end

app/models/quote.rb
class Quote < ApplicationRecord
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: %i[ show edit update destroy ]

  # GET /quotes or /quotes.json
  def index
    @quotes = Quote.all
  end

  # GET /quotes/1 or /quotes/1.json
  def show
  end

  # GET /quotes/new
  def new
    @quote = Quote.new
  end

  # GET /quotes/1/edit
  def edit
  end

  # POST /quotes or /quotes.json
  def create
    @post = Post.new(post_params)
    if NewGoogleRecaptcha.human?(
        params[:new_google_recaptcha_token],
        "checkout",
        NewGoogleRecaptcha.minimum_score,
        @post
      ) && @post.save
      redirect_to @post, notice: 'Post was successfully created.'
    else
      render :new
    end
  end
  
  
  def create
    @quote = Quote.new(quote_params)
    # # Ping slack channel when a user's email is created
    # if @user = User.create(user_params)
    #   SLACK_NOTIFIER.ping("New user: #{@user.email}", username: 'RocketElevators', icon_emoji: ':rocket:')

    my_uri = "https://#{ENV['FRESHDESK_DOMAIN']}.freshdesk.com/api/v2/tickets"
    my_key = ENV['FRESHDESK_API_KEY']

    respond_to do |format|
      if @quote.save
        format.html { redirect_to '/',  notice: "Thank you! Your quote was successfully submitted."}
        format.json { render :show, status: :created, location: @quote }

        data_hash = {
          :subject => "New Request Quote from #{@quote.company_name}",
          :description => building_description(@quote.building_type, @quote),
          :email => "#{@quote.email}",
          :type => "Feature Request",
          :priority => 1,
          :status => 2,
          :custom_fields => {
            "cf_comment": "A new quote request for #{@quote.building_type}. The company #{@quote.company_name} can be reached at email #{@quote.email}."
          }
        }
        
        data_json = JSON.generate(data_hash)

        req = RestClient::Request.execute(
          method: :post,
          url: my_uri,
          user: my_key,
          payload: data_json,
          headers: {'Content-Type' => 'application/json'}
        )

      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotes/1 or /quotes/1.json
  def update
    respond_to do |format|
      if @quote.update(quote_params)
        format.html { redirect_to quote_url(@quote), notice: "Quote was successfully updated." }
        format.json { render :show, status: :ok, location: @quote }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1 or /quotes/1.json
  def destroy
    @quote.destroy

    respond_to do |format|
      format.html { redirect_to quotes_url, notice: "Quote was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def quote_params
      params.require(:quote).permit(:building_type, :num_apts, :num_floors, :num_base, :num_comp, :num_park, :num_elev, :num_corps, :max_occ, :b_hours, :product_line, :unit_price, :elev_cost, :install_fee, :total_cost, :email, :company_name, :estimated_elev)
    end

    def building_description(building_type, quote)
      case building_type
      when "Residential"
        description = "Submission details as follows. Number of Apartments: #{quote.num_apts}, Number of Floors: #{quote.num_floors}, Number of Basements: #{quote.num_base}, Estimated Number of Elevators: #{quote.estimated_elev}, Product Line: #{quote.product_line}, Total Cost: #{quote.total_cost}"
      when "Commercial"
        description = "Submission details as follows. Number of Floors: #{quote.num_floors}, Number of Basements: #{quote.num_base}, Number of Companies: #{quote.num_comp}, Number of Parking Spots: #{quote.num_park}, Estimated Number of Elevators: #{quote.estimated_elev}, Product Line: #{quote.product_line}, Total Cost: #{quote.total_cost}"
      when "Corporate"
        description = "Submission details as follows. Number of Floors: #{quote.num_floors}, Number of Basements: #{quote.num_base}, Number of Parking Spots: #{quote.num_park}, Number of Corporation: #{quote.num_corps}, Maximum Occupancy: #{quote.max_occ}, Estimated Number of Elevators: #{quote.estimated_elev}, Product Line: #{quote.product_line}, Total Cost: #{quote.total_cost}"
      when "Hybrid"
        description = "Submission details as follows. Number of Floors: #{quote.num_floors}, Number of Basements: #{quote.num_base}, Number of Companies: #{quote.num_comp}, Number of Parking Spots: #{quote.num_park}, Maximum Occupancy: #{quote.max_occ}, Business Hours: #{quote.b_hours}, Estimated Number of Elevators: #{quote.estimated_elev}, Product Line: #{quote.product_line}, Total Cost: #{quote.total_cost}"
      end
    end



end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/quotes/_form.html.erb
<!-- PAGE HEADER BREADCRUMBS -->
<section class="page-header page-header-xs parallax parallax-3" style="background-image:url(<%= asset_path 'rocketElevators/imgpattern2.jpg' %>)">
  <div class="overlay dark-2"></div>
    <div class="container">
        <h1 style="text-shadow:rgb(0 0 0 / 30%) 3px 3px 5px"><strong>REQUEST QUOTE</strong></h1>
        <ol class="breadcrumb">
            <li><a id="rockets-home" href="index.html">Home</a></li>
            <li class="active">Request Quote</p></li>
        </ol>
    </div>
</section>
<!-- /PAGE HEADER BREADCRUMS -->

<!-- PARALLAX -->
<section class="parallax parallax-2" style="background-image: url(<%= asset_path "rocketElevators/businessSince.jpeg" %>);">
  <div class="overlay dark-7"></div>
  <div class="container">
      <div class="text-left">
          <h3 style="text-shadow:rgb(0 0 0 / 30%) 3px 3px 5px">
              Get Estimated Price by Building Type
          </h3>
          <h4 style="color:rgb(170, 69, 69); text-shadow:rgb(0 0 0 / 30%) 3px 3px 5px">
              QUESTIONS? 
              <%= link_to "CONTACT US", root_path(anchor: 'contact'), class: "btn btn-outline-primary btn-lg", style: "margin-left: 20px; color: white;"%>
          </h4>
      </div>
  </div>
</section>
<!-- /PARALLAX -->

    <!-- RECAPCHA -->
    <%= content_for :recaptcha_js do %>
        <%= include_recaptcha_js %>
    <% end %>
    <!-- /RECAPCHA -->

<!-- FORM -->
<section>
    <div class="container">
        <%= form_with(model: quote, local: true) do |form| %>

            <div class="select-building-type card card-default">
                <div class="card-heading card-heading-transparent">
                    <label for="building-type" class="card-title"> 
                        <h3>
                            <span style="color:rgb(10, 101, 160); font-weight:bolder">STEP 1 |</span> Select Type of Building
                        </h3> 
                    </label>
                </div>
                <div class="card-block" style="margin: 20px">
                    <%= form.select :building_type, ['---Select---',['Residential', 'residential', :id => 'residential'], ['Commercial', 'commercial', :id => 'commercial'], ['Corporate', 'corporate', :id => 'corporate'], ['Hybrid', 'hybrid', :id => 'hybrid']], {}, class: "form-control pointer required", id: "building_type", name: "building_type" %>  
                    <%= form.text_field :building_type, id: "submit_building_type", :readonly => true, :hidden => true %>
                </div>
            </div>
              
            <div class="estimate-num-elv card card-default"  style="display: none;"> 
                <div class="card-heading step-description">
                    <h3>
                        <span style="color:rgb(10, 101, 160); font-weight:bolder">STEP 2 |</span> Provide Building Information
                    </h3>
                </div>
                <div class="card-block">
                    <% if quote.errors.any? %>
                        <div id="error_explanation">
                            <h2><%= pluralize(quote.errors.count, "error") %> prohibited this quote from being saved:</h2>
                            <ul>
                                <% quote.errors.full_messages.each do |message| %>
                                    <li><%= message %></li>
                                <% end %>
                            </ul>
                        </div>
                    <% end %>

                    <div class="row d-none" style="margin: 20px">
                        <div id="number-of-floors" class="col-4 residential commercial corporate hybrid">
                            <label><h4>Number of Floors</h4></label>
                            <%= form.number_field :num_floors, min: "0", max: "1000", class:"form-control" %>
                        </div>
                        <div id="number-of-basements" class="col-4 residential commercial corporate hybrid">
                            <label><h4>Number of Basements</h4></label>
                            <%= form.number_field :num_base, min: "0", max: "1000", class:"form-control" %>
                        </div>
                        <div id="number-of-apartments" class="col-4 residential">
                            <label><h4>Number of Appartments</h4></label>
                            <%= form.number_field :num_apts, min: "0", max: "1000", class:"form-control" %>
                        </div>
                        <div id="number-of-companies" class="col-4 commercial hybrid">
                            <label><h4>Number of Companies</h4></label>
                            <%= form.number_field :num_comp, min: "0", max: "1000", class:"form-control" %>
                        </div>
                        <div id="number-of-parking-spots" class="col-4 commercial corporate hybrid">
                            <label><h4>Number of Parking Spots</h4></label>
                            <%= form.number_field :num_park, min: "0", max: "1000", class:"form-control" %>
                        </div>
                        <div id="number-of-elevators" class="col-4 commercial">
                            <label><h4>Number of Elevators</h4></label>
                            <%= form.number_field :num_elev, min: "0", max: "1000", class:"form-control" %>
                        </div>
                        <div id="number-of-corporations" class="col-4 corporate">
                            <label><h4>Number of Corporations</h4></label>
                            <%= form.number_field :num_corps, min: "0", max: "1000", class:"form-control" %>
                        </div>
                        <div id="maximum-occupancy" class="col-4 corporate hybrid">
                            <label><h4>Maximum Occupancy</h4></label>
                            <%= form.number_field :max_occ, min: "0", max: "1000", class:"form-control" %>
                        </div>
                        <div id="business-hours" class="col-4 hybrid">
                            <label><h4>Business Hours</h4></label>
                            <%= form.number_field :b_hours, min: "0", max: "24", class:"form-control" %>
                        </div>                
                    </div>

                    <div class="row" style="margin: 20px" id="elevator-amount">
                        <div class="col-6">
                            <label><h4 style="margin-bottom: 0px">Number of Elevators Required (Minimum of 1):</h4></label>
                            <%# <input class="form-control" type="text" readonly>	 %>
                            <%= form.number_field :estimated_elev, id: "submit_estimated_elev", class: "form-control", :readonly => true%>
                            <p style="margin-bottom: 0px;">* With exception for commercial buildings</p>
                        </div>
                    </div>		
                </div>
            </div>

            <div class="product-line card card-default" style="display: none;">
                <div class="card-heading card-heading-transparent">
                    <h3><span style="color:rgb(10, 101, 160); font-weight:bolder">STEP 3 |</span> Select Product Line</h3>
                    <p style="margin-bottom: 0px;">* Excluding tax and offers (if applicable)</p>
                    <p style="color: rgb(170, 69, 69); display: none; margin-bottom: 0px;" id="warning">Complete Step 2 to Estimate Price</p> 
                </div>

                <div class="card-block">
                    <div class='radio-btns row'>
                        <div class="col-4" style="display:flex; justify-content: center;">
                            <label class="standard radio">
                                <input type="radio" name="product-line" id="standard">
                                <i></i> STANDARD ✭
                            </label>
                        </div>
                        <div class="col-4" style="display:flex; justify-content: center;">
                            <label class="premium radio">
                                <input type="radio" name="product-line" id="premium">
                                <i></i> PREMIUM ✭✭
                            </label>
                        </div>
                        <div class="col-4" style="display:flex; justify-content: center;">
                            <label class="excelium radio">
                                <input type="radio" name="product-line" id="excelium">
                                <i></i> EXCELIUM ✭✭✭
                            </label>
                        </div>
                    </div>
                </div>
                <%= form.text_field :product_line, id: "submit_product_line", :readonly => true, :hidden => true %>
            </div>

            <div class="final-pricing-display card card-default" style="display: none;">
                <div class="card-heading card-heading-transparent">
                    <h3><span style="color:rgb(10, 101, 160); font-weight:bolder">STEP 4 |</span> Estimated Pricing</h3>
                    <p style="margin-bottom: 0px;">* Excluding tax and offers (if applicable)</p>
                    <p style="color: rgb(170, 69, 69); display: none; margin-bottom: 0px;" id="warning">Complete Step 2 to Estimate Price</p> 
                </div>

                <div class="card-block">
                    <div class="pricing-display row mega-price-table" style="margin: 20px">
                        <div id="elevator-unit-price" class="col-md-3 col-sm-6 block">
                            <div class="pricing">
                                <div class="pricing-head">
                                    <h3>Unit Price</h3>
                                    <small>for Product Line</small>
                                </div>
                                <h4>
                                    <%= form.text_field :unit_price, class:"form-control", style:"background: none; text-align:center; border: none; font-size:x-large", :readonly => true %>
                                </h4>
                            </div>
                        </div>

                        <div id="elevator-total-price" class="col-md-3 col-sm-6 block">
                            <div class="pricing">
                                <div class="pricing-head">
                                    <h3>Elevator Cost</h3>					
                                    <small>Based on no. of Elevator Required</small>
                                </div>
                                <h4>
                                    <%= form.text_field :elev_cost, class:"form-control", style:"background: none; text-align:center; border: none; font-size:x-large", :readonly => true %>
                                </h4>
                            </div>
                        </div>

                        <div  id="installation-fees"  class="col-md-3 col-sm-6 block">
                            <div class="pricing">
                                <div class="pricing-head">
                                    <h3>Installation Fee</h3>
                                    <small>Percent Elevator Cost</small>
                                </div>
                                <h4>
                                    <%= form.text_field :install_fee, class:"form-control", style:"background: none; text-align:center; border: none; font-size:x-large", :readonly => true %>
                                </h4>
                            </div>
                        </div>

                        <div id="final-price" class="col-md-3 col-sm-6 block">
                            <div class="pricing">
                                <div class="pricing-head">
                                    <h3>Total Cost</h3>
                                    <small>Elevator plus Installation Fee</small>					
                                </div>
                                <h4>
                                    <%= form.text_field :total_cost, class:"form-control", style:"background: none; text-align:center; border: none; font-size:x-large", :readonly => true %>
                                </h4>
                            </div>
                        </div>
                    </div>
                </div>
               
            </div>

            <div class="user-info card card-default" style="display: none;"> 
                 <div class="card-heading card-heading-transparent">
                    <h3><span style="color:rgb(10, 101, 160); font-weight:bolder">STEP 5 |</span> User Information </h3>
                </div>
                <div class="card-block">
                    <div class="row">
                        <div class="col-md-6">
                            <label for="company_name">Company Name</label>
                            <%= form.text_field :company_name, id: "company-name",class: "form-control", :required => true %>
                        </div>
                        <div class="col-md-6">
                            <label for="email">Email</label>
                            <%= form.text_field :email, class: "form-control", id: "user-email", :required => true %>
                        </div>
                    </div>
                </div>
            </div>
            <%= recaptcha_action('checkout') %>
            <div class="actions submit-form" style="display: none;">
                <%= form.submit class: "btn btn-primary btn-lg" %>
            </div>
           
        <% end %> 
    </div>
</section>
<!-- /FORM -->

app/views/quotes/edit.html.erb
<h1>Editing Quote</h1>

<%= render 'form', quote: @quote %>

<%= link_to 'Show', @quote %> |
<%= link_to 'Back', quotes_path %>

app/views/quotes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Quotes</h1>

<table>
  <thead>
    <tr>
      <th>Building type</th>
      <th>Num apts</th>
      <th>Num floors</th>
      <th>Num base</th>
      <th>Num comp</th>
      <th>Num park</th>
      <th>Num elev</th>
      <th>Num corps</th>
      <th>Max occ</th>
      <th>B hours</th>
      <th>Product line</th>
      <th>Unit price</th>
      <th>Elev cost</th>
      <th>Install fee</th>
      <th>Total cost</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quotes.each do |quote| %>
      <tr>
        <td><%= quote.building_type %></td>
        <td><%= quote.num_apts %></td>
        <td><%= quote.num_floors %></td>
        <td><%= quote.num_base %></td>
        <td><%= quote.num_comp %></td>
        <td><%= quote.num_park %></td>
        <td><%= quote.num_elev %></td>
        <td><%= quote.num_corps %></td>
        <td><%= quote.max_occ %></td>
        <td><%= quote.b_hours %></td>
        <td><%= quote.product_line %></td>
        <td><%= quote.unit_price %></td>
        <td><%= quote.elev_cost %></td>
        <td><%= quote.install_fee %></td>
        <td><%= quote.total_cost %></td>
        <td><%= link_to 'Show', quote %></td>
        <td><%= link_to 'Edit', edit_quote_path(quote) %></td>
        <td><%= link_to 'Destroy', quote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Quote', new_quote_path %>

app/views/quotes/new.html.erb
<%= render 'form', quote: @quote %>

app/views/quotes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Building type:</strong>
  <%= @quote.building_type %>
</p>

<p>
  <strong>Num apts:</strong>
  <%= @quote.num_apts %>
</p>

<p>
  <strong>Num floors:</strong>
  <%= @quote.num_floors %>
</p>

<p>
  <strong>Num base:</strong>
  <%= @quote.num_base %>
</p>

<p>
  <strong>Num comp:</strong>
  <%= @quote.num_comp %>
</p>

<p>
  <strong>Num park:</strong>
  <%= @quote.num_park %>
</p>

<p>
  <strong>Num elev:</strong>
  <%= @quote.num_elev %>
</p>

<p>
  <strong>Num corps:</strong>
  <%= @quote.num_corps %>
</p>

<p>
  <strong>Max occ:</strong>
  <%= @quote.max_occ %>
</p>

<p>
  <strong>B hours:</strong>
  <%= @quote.b_hours %>
</p>

<p>
  <strong>Product line:</strong>
  <%= @quote.product_line %>
</p>

<p>
  <strong>Unit price:</strong>
  <%= @quote.unit_price %>
</p>

<p>
  <strong>Elev cost:</strong>
  <%= @quote.elev_cost %>
</p>

<p>
  <strong>Install fee:</strong>
  <%= @quote.install_fee %>
</p>

<p>
  <strong>Total cost:</strong>
  <%= @quote.total_cost %>
</p>

<%= link_to 'Edit', edit_quote_path(@quote) %> |
<%= link_to 'Back', quotes_path %>