config/routes.rb
Rails.application.routes.draw do
  resources :interventions
  resources :leads  
  devise_for :users

  # get "leads", to: "leads#new"
  # post "leads", to: "leads#create"
  # get "leads/index", to: "leads#index"
  
  post "/", to: "leads#create"
  get "quotes", to: "quotes#new"
  post "quotes", to: "quotes#create"

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "home#index"
  get "commercial",  to: "home#commercial"
  get "residential", to: "home#residential"
  get "interventions", to: "interventions#interventions"
  
  resources :synthesized_messages
end
  
  #Dropdown dynamic menu

  Rails.application.routes.draw do

    resources :testing_buttons
    get 'get_building_by_customer/:customer_id', to: 'interventions#get_building_by_customer'  
    get 'get_battery_by_building/:building_id', to: 'interventions#get_battery_by_building'  
    get 'get_column_by_battery/:battery_id', to: 'interventions#get_column_by_battery' 
    get 'get_elevator_by_column/:column_id', to: 'interventions#get_elevator_by_column'  
    get '/building_search' => 'application#building_search'
  
   end

app/views/shared/_footer.html.erb
<!-- FOOTER -->
<footer id="footer">
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <h3 class="letter-spacing-1">WHY US?</h3>
                <p>
                    We have the conviction that we create the most innovative and reliable products on the market. Contact us today for any questions you might have.
                </p>
                <h2>(418) 555-1234</h2>
            </div>

            <div class="col-md-4">
                <h3 class="letter-spacing-1">KEEP IN TOUCH</h3>
                <p>Subscribe to Our Newsletter to get Important News & Offers</p>
                
                <form id="subscribe-form" onsubmit="showPopup()">
                    <div class="input-group">
                        <span class="input-group-addon">
                            <i class="fa fa-envelope"></i>
                        </span>
                        <input type="email" id="email" name="email" class="form-control required" placeholder="Enter your Email">
                        <span class="input-group-btn">
                            <button class="btn btn-primary" type="submit">
                                Subscribe
                            </button>
                        </span>
                    </div>
                </form>

            </div>
        </div>
    </div>
    <div class="copyright">
        <div class="container">
            &copy; All Rights Reserved, Rocket Elevators <br>
            Disclaimer: This website was developed for educational purpose only. 
            The content presented herein is fictional. 
        </div>
    </div>
</footer>
<!-- /FOOTER -->

app/views/shared/_modal.html.erb
<!-- MODAL -->
<div class="modal fade" id="success-message" role="dialog">
    <div class="modal-dialog">				
    <div class="modal-content">
        <div class="modal-header" style="background-color: rgb(10, 101, 160);">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h3 class="modal-title" style="color: #fff; text-align: center;"> 		
            <i class="fa fa-envelope" style="color: #fff;"></i>
            MESSAGE SENT!
        </h3>
        </div>
        <div class="modal-body">
            <h4 style="text-align: center;">
                Thank you for contacting Rocket Elevators. <br> 
                Your inquiry is our top priority and <br> 
                we will get back to you shortly. 
            </h4>
            <%= image_tag "rocketElevators/rocketLogo.png", class: "img-fluid", style: "display: block;
            margin-left: auto; margin-right: auto;", width: "200px"%>
        </div>
        <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
    </div>
    
    </div>
</div>

<div class="modal fade" id="subscribe-message" role="dialog">
    <div class="modal-dialog">				
    <div class="modal-content">
        <div class="modal-header" style="background-color: rgb(10, 101, 160);">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h3 class="modal-title" style="color: #fff; text-align: center;"> 		
            🔔 SUBSCRIBED!
        </h3>
        </div>
        <div class="modal-body">
            <h4 style="text-align: center;">
                Thank you for subscribing to our newsletter! <br> 
            </h4>
        </div>
        <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
    </div>
    
    </div>
</div>
<!-- /MODAL -->

app/views/shared/_navigation.html.erb
<!-- TOP NAVIGATION -->
<div id="header" class="navbar-toggleable-md sticky header-md clearfix">
    <% if user_signed_in? %>
        <section class="page-header page-header-xs parallax parallax-2" style="background-color: #0A65A0; padding-top: 5px; padding-bottom: 5px;">
            <div class="container">
                <h1 class="float-right" style="text-shadow:rgb(0 0 0 / 30%) 3px 3px 3px;"><strong>Welcome! <%= current_user.first_name %> <%= current_user.last_name %> </strong></h1>
            </div>
        </section>
    <% end %>

    <header id="topNav">
        <div class="container">
            <!-- Mobile Menu Button -->
            <button class="btn btn-mobile" data-toggle="collapse" data-target=".nav-main-collapse">
                <i class="fa fa-bars"></i>
            </button>

            <!-- Logo -->
            <a><%= link_to image_tag("rocketElevators/rocketLogo.png"), root_path, class:"logo float-left scrollTo" %></a>
            
            <div class="navbar-collapse collapse float-right nav-main-collapse submenu-dark">
                <nav class="nav-main">
                    <ul id="topMain" class="nav nav-pills nav-main nav-onepage">
                        <li><%= link_to "HOME", root_path(anchor: 'top')%></li>
                        <li class="dropdown">
                            <%= link_to "SERVICES", root_path(anchor: 'services'), class: "dropdown-toggle"%>
                            <ul class="dropdown-menu">
                                <li class="dropdown"><%= link_to "RESIDENTIAL", residential_path %></li>
                                <li class="dropdown"><%= link_to "COMMERCIAL", commercial_path %></li>
                                <li class="dropdown"><%= link_to "PORTFOLIO", root_path(anchor: 'portfolio') %></li>
                            </ul>
                        </li>
                        <li><%= link_to "NEWS", root_path(anchor: 'news') %></li>
                        <li><%= link_to "CLIENTS", root_path(anchor: 'clients') %></li>
                        <li><%= link_to "QUOTE", quotes_path %></li>
                        <li><%= link_to "CONTACT", root_path(anchor: 'contact') %></li>
                        
                        <% if current_user %>
                            <li><%= link_to "INTERVENTION", interventions_path %></li>
                            <li><%= link_to "SIGN OUT", destroy_user_session_path, method: :delete %></li>
                            <% if Employee.where(user_id: current_user.id).exists? %>
                                <li><%= link_to "ADMIN", rails_admin_path %></li>
                                <%# <button onclick="pollyGreet()" class="btn btn-danger">
                                    <strong>BRIEFING</strong>
                                </button>
                                <%= audio_tag "greetings.mp3", id: "greetings" %>
                            <% end %>
                        <% else %>
                            <li><%= link_to "SIGN UP", new_user_registration_path %></li>
                            <li><%= link_to "SIGN IN", new_user_session_path %></li>
                        <% end %>
                    </ul>
                </nav>
            </div>
        </div>
    </header>
<!-- TOP NAV -->
</div>