config/routes.rb
Rails.application.routes.draw do
  resources :interventions
  resources :leads  
  devise_for :users

  # get "leads", to: "leads#new"
  # post "leads", to: "leads#create"
  # get "leads/index", to: "leads#index"
  
  post "/", to: "leads#create"
  get "quotes", to: "quotes#new"
  post "quotes", to: "quotes#create"

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "home#index"
  get "commercial",  to: "home#commercial"
  get "residential", to: "home#residential"
  get "interventions", to: "interventions#interventions"
  
  resources :synthesized_messages
end
  
  #Dropdown dynamic menu

  Rails.application.routes.draw do

    resources :testing_buttons
    get 'get_building_by_customer/:customer_id', to: 'interventions#get_building_by_customer'  
    get 'get_battery_by_building/:building_id', to: 'interventions#get_battery_by_building'  
    get 'get_column_by_battery/:battery_id', to: 'interventions#get_column_by_battery' 
    get 'get_elevator_by_column/:column_id', to: 'interventions#get_elevator_by_column'  
    get '/building_search' => 'application#building_search'
  
   end

app/models/intervention.rb
class Intervention < ApplicationRecord
end

app/controllers/interventions_controller.rb
class InterventionsController < ApplicationController
  before_action :set_intervention, only: %i[ show edit update destroy ]

  
  # GET /interventions or /interventions.json
  def index
    @interventions = Intervention.all
  end

  # GET /interventions/1 or /interventions/1.json
  def show
  end

  # GET /interventions/new
  def new
    @intervention = Intervention.new
    
    @customer = Customer.all
    @building = Building.all
    @battery = Battery.all
    @column = Column.all
    @elevator = Elevator.all
    @employee = Employee.all


    
    @actualuser = current_user.first_name + " " + current_user.last_name


  end

  # GET /interventions/1/edit
  def edit
  end

  # POST /interventions or /interventions.json
  def create
 
    @intervention = Intervention.new(intervention_params)

    # before_create do
    #       
    # end

    # (author: @current_user, customerID: customerID, buildingID: buildingID, batteryID: batteryID, columnID: columnID, elevatorID: elevatorID, employeeID: employeeID, start_date_and_time_of_the_intervention: start_date_and_time_of_the_intervention, end_date_and_time_of_the_intervention: end_date_and_time_of_the_intervention, result: result, report: report, status: status)
    # intervention_params

    respond_to do |format|
      if @intervention.save
        format.html { redirect_to intervention_url(@intervention), notice: "Intervention was successfully created." }
        format.json { render :show, status: :created, location: @intervention }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @intervention.errors, status: :unprocessable_entity }
      end
    end
  end

  def create
    puts "create intervention function works ---------------------------------------------"
    @intervention = Intervention.new(intervention_params)


    my_uri = "https://#{ENV['FRESHDESK_DOMAIN']}.freshdesk.com/api/v2/tickets"
    my_key = ENV['FRESHDESK_API_KEY']

    respond_to do |format|
      if @intervention.save
        format.html { redirect_to "/", notice: "Thank you. We will communicate with you shortly!" }
        format.json { render :show, status: :created, location: @intervention }

        # attachment_exists = @lead.attached_file_stored_as_binary.attached?
        # user_is_customer = Customer.where(email_of_the_company_contact: "#{@lead.email}").present? || Customer.where(technical_manager_email_for_service: "#{@lead.email}").present?
        site = RestClient::Resource.new(my_uri, my_key, 'X')
        # client = RestClient::Resource.new

        # if attachment_exists
          
        #   attachment = @lead.attached_file_stored_as_binary.attachment
        #   blob_data = @lead.attached_file_stored_as_binary.blob
        #   blob_path = blob_data.service.path_for(blob_data.key)
          
          # NOTE: FRESHDESK
          # data_hash = {
          #     status: 2,
          #     priority: 1,
          #     subject: "#{@lead.full_name} from #{@lead.company_name}", 
          #     description: "The contact #{@lead.full_name}  from company #{@lead.company_name} can be reached at email #{@lead.email} and at phone number #{@lead.phone}. #{@lead.department_in_charge_of_elevators} has a project named #{@lead.project_name} which would require contribution from Rocket Elevators.\nProject Description: #{@lead.project_description}\n#{@lead.message}.\nThe Contact uploaded an attachment",
          #     email: "#{@lead.email}",
          #     type:"Question",
          #     attachments: [File.new(blob_path, "rb")]
          #   }

          #   # data_json = JSON.generate(data_hash)
          #   site.post(data_hash)

            # if user_is_customer
              # NOTE: DROPBOX
              # authenticator = DropboxApi::Authenticator.new(ENV["DROPBOX_KEY"], ENV["DROPBOX_SECRET"])
              # authenticator.auth_code.authorize_url(token_access_type: "offline")
              # access_token = authenticator.auth_code.get_token(ENV["DROPBOX_ACCESS_CODE"])
              # client = DropboxApi::Client.new(access_token: access_token)
        #       client = DropboxApi::Client.new
        #       folder_exists = client.search("#{@lead.full_name}").matches[0]
        #       client.create_folder("/#{@lead.full_name}") unless folder_exists
        #       file_path = "/#{@lead.full_name}/#{blob_data.filename.sanitized}"
        #       response = client.upload(file_path, blob_data.download)
        #       attachment.purge if response.id
        #     end
          
        # else
          # attachment does not exist or user is not customer 
          data_hash = {
            status: 2,
            priority: 1,
            subject: "#{@intervention.result} from #{@intervention.author}", 
            description: 
            "The requester #{@intervention.author} started a new intervention
            for company #{@intervention.customerID} //
            On builging ID #{@intervention.buildingID} // 
            On battery ID #{@intervention.batteryID} //
            On column ID #{@intervention.columnID} //
            On elevator ID #{@intervention.elevatorID} //
            Job is done by employee ID #{@intervention.employeeID} //
            The job description #{@intervention.report}
              ",
            
            email: "#{current_user.email}",
            type:"Question"
          }
          
          data_json = JSON.generate(data_hash)
          # site.post(data_json)
          RestClient::Request.execute(
            method: :post,
            url: my_uri,
            user: my_key,
            password: 'X',
            payload: data_json,
            headers: {"Content-Type" => "application/json"},
          )

        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @intervention.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /interventions/1 or /interventions/1.json
  def update
    respond_to do |format|
      if @intervention.update(intervention_params)
        format.html { redirect_to intervention_url(@intervention), notice: "Intervention was successfully updated." }
        format.json { render :show, status: :ok, location: @intervention }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @intervention.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /interventions/1 or /interventions/1.json
  def destroy
    @intervention.destroy

    respond_to do |format|
      format.html { redirect_to interventions_url, notice: "Intervention was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def get_building_by_customer
    @building = Building.where("customer_id = ?", params[:customer_id])
    respond_to do |format|
        format.json { render :json => @building }
    end
  end

  def get_battery_by_building
    @battery = Battery.where("building_id = ?", params[:building_id])
    respond_to do |format|
        format.json { render :json => @battery }
    end
  end

  def get_column_by_battery
    @column = Column.where("battery_id = ?", params[:battery_id])
    respond_to do |format|
        format.json { render :json => @column }
    end
  end

  def get_elevator_by_column
    @elevator = Elevator.where("column_id = ?", params[:column_id])
    respond_to do |format|
        format.json { render :json => @elevator }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_intervention
      @intervention = Intervention.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def intervention_params
      params.require(:intervention).permit(:author, :customerID, :buildingID, :batteryID, :columnID, :elevatorID, :employeeID, :report)
    end
end

app/helpers/interventions_helper.rb
module InterventionsHelper
end

app/views/interventions/_form.html.erb
<!-- PAGE HEADER BREADCRUMBS -->
<section class="page-header page-header-xs parallax parallax-3" style="background-image:url(<%= asset_path 'rocketElevators/imgpattern2.jpg' %>)">
  <div class="overlay dark-2"></div>
    <div class="container">
        <h1 style="text-shadow:rgb(0 0 0 / 30%) 3px 3px 5px"><strong>New intervention call</strong></h1>
        <ol class="breadcrumb">
            <li><a id="rockets-home" href="index.html">Home</a></li>
  
        </ol>
    </div>
</section>
<!-- /PAGE HEADER BREADCRUMS -->

<!-- FORM -->
<section>
    <div class="container">
      <%= form_with(model: intervention, local: true) do |form| %>
        <% if intervention.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(intervention.errors.count, "error") %> prohibited this intervention from being saved:</h2>

            <ul>
            <% intervention.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

 <!-- customer -->
            
            <div class="card card-default">
                <div class="card-heading card-heading-transparent">
                    <label for="building-type" class="card-title"> 
                        <h3>
                            <span style="color:rgb(10, 101, 160); font-weight:bolder">STEP 1 |</span> Select customer
                        </h3> 
                    </label>
                </div>
                <div class="card-block" style="margin: 20px">

                <select style="max-width: 150px;" id="customer_select" <%= form.select(:customerID) do %>  >
                    <option selected>Customer</option>
                        <%= @customer.each do |c| %>
                    <option value="<%= c.id %>"><%= c.company_name %></option>
                        <% end %>
                    <% end %>  
                </select> 
                </div>
            </div>
    
  <!-- building -->

            <div class="card card-default">
                <div class="card-heading card-heading-transparent">
                    <label for="building-type" class="card-title"> 
                        <h3>
                            <span style="color:rgb(10, 101, 160); font-weight:bolder">STEP 2 |</span> Select Building
                        </h3> 
                    </label>
                </div>
                <div class="card-block" style="margin: 20px"> 
                <select style="max-width: 150px;" id="building_select" class="custom-select mb-0 mr-sm-0 mb-sm-0" <%= form.select(:buildingID) do %>  >
                    <option selected>Building</option>
                        <%= @building.each do |b| %>
                    <option value="<%= b.id %>"><%= b.id %></option>
                        <% end %>
                    <% end %>  
                </select> 
                </div>
            </div>

  <!-- battery -->

            <div class="card card-default">
                <div class="card-heading card-heading-transparent">
                    <label for="building-type" class="card-title"> 
                        <h3>
                            <span style="color:rgb(10, 101, 160); font-weight:bolder">STEP 3 |</span> Select Battery
                        </h3> 
                    </label>
                </div>
                <div class="card-block" style="margin: 20px">

                <select style="max-width: 150px;" id="battery_select" class="custom-select mb-0 mr-sm-0 mb-sm-0" <%= form.select(:batteryID) do %>  >
                    <option selected>Battery</option>
                        <%= @battery.each do |b| %>
                    <option value="<%= b.id %>"><%= b.id %></option>
                        <% end %>
                    <% end %>  
                </select> 
                </div>
            </div>
  
  <!-- column -->

              <div class="card card-default">
                <div class="card-heading card-heading-transparent">
                    <label for="building-type" class="card-title"> 
                        <h3>
                            <span style="color:rgb(10, 101, 160); font-weight:bolder">STEP 4 |</span> Select Column
                        </h3> 
                    </label>
                </div>
                <div class="card-block" style="margin: 20px">

                <select style="max-width: 150px;" id="column_select" class="custom-select mb-0 mr-sm-0 mb-sm-0" <%= form.select(:columnID) do %>  >
                    <option selected>Column</option>
                        <%= @column.each do |b| %>
                    <option value="<%= b.id %>"><%= b.id %></option>
                        <% end %>
                    <% end %>  
                </select> 
                </div>
              </div>
    
  <!-- elevator -->

            <div class="card card-default">
                <div class="card-heading card-heading-transparent">
                    <label for="building-type" class="card-title"> 
                        <h3>
                            <span style="color:rgb(10, 101, 160); font-weight:bolder">STEP 5 |</span> Select Elevator
                        </h3> 
                    </label>
                </div>
                <div class="card-block" style="margin: 20px">

                <select style="max-width: 150px;" id="elevator_select" class="custom-select mb-0 mr-sm-0 mb-sm-0" <%= form.select(:elevatorID) do %>  >
                    <option selected>Elevator</option>
                        <%= @elevator.each do |b| %>
                    <option value="<%= b.id %>"><%= b.id %></option>
                        <% end %>
                    <% end %>  
                </select> 
                    </div>
            </div>
         
  <!-- employee -->

            <div class="card card-default">
                <div class="card-heading card-heading-transparent">
                    <label for="building-type" class="card-title"> 
                        <h3>
                            <span style="color:rgb(10, 101, 160); font-weight:bolder">STEP 6 |</span> Whats the employee ID?
                        </h3> 
                    </label>
                </div>
                <div class="card-block" style="margin: 20px">
               
                      <%= form.select :employeeID, :include_blank => "None" do %>
                           <% @employee.each do |l| -%>
                           <%= content_tag(:option, l.id, value: l.id) %>
                       <% end %>
                    <% end %>
                </div>
            </div>

  <!-- start date and time | Don't show -->

  <!-- end date and time | Don't show -->

  <!-- result | Don't show -->

  <!-- report -->
            <div class="card card-default">
                <div class="card-heading card-heading-transparent">
                    <label for="building-type" class="card-title"> 
                        <h3>
                            <span style="color:rgb(10, 101, 160); font-weight:bolder">STEP 7 |</span> Report
                        </h3> 
                    </label>
                </div>
                <div class="card-block" style="margin: 20px">
                    
                    <%= form.text_area(:report, size: '50x10') %>

                </div>
            </div>
  <!-- status | Don't show -->
  
  <!-- Author | READ only-->
            <%= "This form has been fill by " %>
            <div>
                <br>
                <%= form.text_field(:author, :readonly=>true, :value=>@actualuser) %>     
                <br>
            <div>

  <!-- Submit button -->
      <div class="actions">
        <br>
        <%= form.submit %>
      </div>
    <% end %>
  </div>
</section>
<!-- /FORM -->

app/views/interventions/edit.html.erb
<h1>Editing Intervention</h1>

<%= render 'form', intervention: @intervention %>

<%= link_to 'Show', @intervention %> |
<%= link_to 'Back', interventions_path %>

app/views/interventions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Interventions</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @interventions.each do |intervention| %>
      <tr>
        <td><%= link_to 'Show', intervention %></td>
        <td><%= link_to 'Edit', edit_intervention_path(intervention) %></td>
        <td><%= link_to 'Destroy', intervention, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Intervention', new_intervention_path %>

app/views/interventions/new.html.erb
<%= render 'form', intervention: @intervention %>

<!-- <%= link_to 'Back', interventions_path %> -->

app/views/interventions/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_intervention_path(@intervention) %> |
<%= link_to 'Back', interventions_path %>